# Generated by Django 5.1.1 on 2024-09-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.IntegerField(default=101410428, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
