# Generated by Django 5.1.1 on 2024-09-15 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_customer_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="phone",
        ),
    ]
