# Generated by Django 5.1.1 on 2024-09-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0003_remove_customer_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.IntegerField(default=708410428, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
