# Generated by Django 5.1.1 on 2024-09-15 13:42

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0004_customer_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                max_length=13,
                unique=True,
                validators=[customers.models.validate_kenyan_phone_number],
            ),
        ),
    ]
