name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Export environment variables
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
        echo "PROD_DB_NAME=${{ secrets.PROD_DB_NAME }}" >> $GITHUB_ENV
        echo "PROD_DB_USER=${{ secrets.PROD_DB_USER }}" >> $GITHUB_ENV
        echo "PROD_DB_PASSWORD=${{ secrets.PROD_DB_PASSWORD }}" >> $GITHUB_ENV
        echo "PROD_DB_HOST=${{ secrets.PROD_DB_HOST }}" >> $GITHUB_ENV
        echo "PROD_DB_PORT=${{ secrets.PROD_DB_PORT }}" >> $GITHUB_ENV
        echo "AT_API_KEY=${{ secrets.AT_API_KEY }}" >> $GITHUB_ENV
        echo "AT_SENDER_ID=${{ secrets.AT_SENDER_ID }}" >> $GITHUB_ENV
        echo "AT_USERNAME=${{ secrets.AT_USERNAME }}" >> $GITHUB_ENV

    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh

    - name: Authenticate with Heroku
      run: |
        echo ${{ secrets.HEROKU_API_KEY }} | heroku auth:token

    - name: Run Django Migrations
      run: |
        python api/manage.py migrate  # Adjust this path if necessary

    - name: Deploy to Heroku
      run: |
        git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
        git push heroku main

    - name: Run Migrations on Heroku
      run: |
        heroku run python api/manage.py migrate --app ${{ secrets.HEROKU_APP_NAME }}
