name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh

    - name: Authenticate with Heroku CLI
      run: |
        echo ${{ secrets.HEROKU_API_KEY }} | heroku auth:token

    - name: Configure Git for Heroku Deployment
      run: |
        git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Deploy to Heroku
      run: |
        git push heroku main

    - name: Run Migrations on Heroku
      run: |
        heroku run python api/manage.py migrate --app ${{ secrets.HEROKU_APP_NAME }}
