name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Create Procfile
      run: |
        echo "web: gunicorn api.wsgi --log-file -" > Procfile
        git add Procfile
        git commit -m "Add Procfile for Heroku" || echo "No changes to commit"

    - name: Set up Heroku environment variables
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku config:set \
          SECRET_KEY="${{ secrets.SECRET_KEY }}" \
          DEBUG="False" \
          ALLOWED_HOSTS="${{ secrets.HEROKU_APP_NAME }}.herokuapp.com" \
          --app ${{ secrets.HEROKU_APP_NAME }}

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.14
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        buildpack: "heroku/python"
        procfile: "web: gunicorn api.wsgi --log-file -"
        justlogin: true

    - name: Push to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        git push https://heroku:$HEROKU_API_KEY@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git HEAD:main --force

    - name: Disable collectstatic
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku config:set DISABLE_COLLECTSTATIC=1 --app ${{ secrets.HEROKU_APP_NAME }}

    - name: Run Migrations on Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku run python api/manage.py migrate --app ${{ secrets.HEROKU_APP_NAME }}